services:
  roma:
    build:
      context: .
      dockerfile: Dockerfile.roma
    container_name: sentient-health-tracker--roma-1
    ports:
      - "5001:5000"                 # host:container  <<<<< change to 5001:5000
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=5000                   # <<<<< match what the app actually uses
      - FLASK_ENV=production
    command: python -m roma_service --host ${HOST:-0.0.0.0} --port ${PORT:-5000}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/api/simple/status || exit 1"]  # <<<<< 5000
      interval: 15s
      timeout: 5s
      retries: 8
    restart: unless-stopped

  health-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentient-health-tracker--health-tracker-1
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-fsS",
             "-H", "x-api-key: ${HEALTH_API_KEY}",
             "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 8
    restart: unless-stopped
